site:
  title: Electrónica, Robótica e IOT con Elixir
  url: https://elixircl.github.io/elixir-robotics
  start_page: "ROOT::index.adoc"

content:
  sources:
  - url: .
    branches: HEAD
    start_path: .

antora:
  extensions:
    - require: '@antora/lunr-extension'

asciidoc:
  extensions:
    - asciidoctor-emoji
    - asciidoctor-kroki
    - '@djencks/asciidoctor-mathjax'
  attributes:
    kroki-fetch-diagram: true
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    highlightjs-theme: monokai
    highlightjs-languages: js, elixir, sql, yaml, html, css
    stem: latexmath

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  # https://gitlab.com/antora/antora-ui-default/-/tree/master/src/partials
  supplemental_files: supplemental-ui/

output:
  dir: docs/
