= FPGA

Un **FPGA** (*Field-Programmable Gate Array*) es un 
**circuito integrado programable** que permite crear **hardware digital personalizado** 
despu茅s de ser fabricado.

A diferencia de un microcontrolador o CPU, un FPGA **no ejecuta instrucciones**, 
sino que **se configura para convertirse en el circuito** dise帽ado.

Un FPGA est谩 compuesto por:

-  **Bloques l贸gicos configurables** (LUTs)
-  **Flip-flops** (memoria b谩sica)
-  **Interconexiones programables**
- 憋 **Relojes y PLLs**
- ヰ **Pines de entrada/salida (I/O)**

Cuando es programado se define **qu茅 hace cada bloque**, c贸mo se **conectan entre s铆**. 
Todo funcionando **en paralelo**.

== 驴En qu茅 se diferencia de un microcontrolador?

.Comparaci贸n entre FPGA y MicroControlador
|====
| FPGA | Microcontrolador 

| Hardware configurable | Hardware fijo 
| Ejecuci贸n paralela | Ejecuci贸n secuencial 
| Muy r谩pido | M谩s lento 
| Se programa con HDL | Se programa con C/C++ 
| Ideal para tiempo real | Ideal para control 
|====

== Programaci贸n

Para programar un FPGA se usan **lenguajes de descripci贸n de hardware (HDL)**. 
Donde se describen los circuitos.

Ejemplos:

- **VHDL**
- **Verilog**
- **SystemVerilog**
- https://github.com/chipsalliance/chisel[Chisel] (https://www.imm.dtu.dk/~masca/chisel-book.html[Libro]).

=== Chisel

Chisel es un lenguaje espec铆fico de dominio (DSL) para describir circuitos de hardware, 
incrustado en Scala. Por su propia naturaleza, proporciona construcciones equivalentes a 
las de Verilog, como m贸dulos, entradas/salidas (Input/Output), registros (Reg), etc. 
De forma problem谩tica para tu pregunta, esto provoca que los ejemplos m谩s b谩sicos de 
Chisel se vean exactamente igual que Verilog y tambi茅n permite que la gente escriba 
Chisel que se parece mucho a Verilog. Esto se utiliza a menudo como argumento para 
descartar Chisel en favor de Verilog.

Chisel forma parte de un framework de compilaci贸n de hardware que se parece 
mucho a LLVM aplicado a la generaci贸n de hardware. El proceso de Chisel a 
Verilog forma parte de un compilador de m煤ltiples etapas. El frontend de 
Chisel compila Chisel a una representaci贸n intermedia de circuitos 
llamada FIRRTL (Flexible Intermediate Representation for RTL). Luego, la etapa 
intermedia de FIRRTL (mid-end) optimiza FIRRTL y aplica transformaciones 
personalizadas definidas por el usuario. Finalmente, la etapa de Verilog 
(back-end) genera c贸digo Verilog a partir del FIRRTL optimizado.

.Ejemplo de C贸digo de Chisel
[source, scala]
----
package hw

import chisel3._
import chisel3.util.MuxCase

class Counter(size: Int) extends Module {
  val io = IO(new Bundle {
    val out = Output(UInt(size.W))
    val ena = Input(Bool())
    val clr = Input(Bool())
  })

  val tmp: UInt = RegInit(0.U(size.W))

  when(reset.asBool) {
    tmp := 0.U
  }.otherwise {
    tmp := MuxCase(tmp, Array(io.clr -> 0.U, io.ena -> (tmp + 1.U)))
  }

  io.out := tmp
}
----

== 驴Para qu茅 se usan los FPGA?

- Procesamiento de se帽ales (DSP)
- Video y visi贸n artificial
- Redes y telecomunicaciones
- Criptograf铆a
- Inteligencia artificial (aceleradores)
- Prototipado de ASIC
- Control industrial de alta velocidad

*Ventajas*

- Ejecuci贸n totalmente paralela  
- Muy baja latencia  
- Reconfigurable  
- Alto rendimiento

*Desventajas*

- M谩s caro que un microcontrolador  
- Mayor consumo  
- Curva de aprendizaje m谩s alta  
- Requiere herramientas especializadas

*Ejemplo*

Un FPGA puede:

- Leer m煤ltiples se帽ales
- Procesarlas **al mismo tiempo**
- Generar salidas en **nanosegundos**

Mientras que un microcontrolador lo har铆a **una por una**.

=== MiSTer FPGA

MiSTer es un proyecto de c贸digo abierto que emula consolas, 
computadoras y placas arcade mediante FPGA. Esto es diferente de la emulaci贸n por 
software, ya que existe la posibilidad de obtener un rendimiento exactamente igual al 
del hardware original.

Aunque la emulaci贸n por software tambi茅n puede llegar a ser muy precisa, 
con la emulaci贸n mediante FPGA es mucho m谩s probable lograr latencia cero, 
lo que la convierte en una opci贸n excelente para personas que utilizan 
tanto pantallas HDMI como monitores CRT.

++++
<iframe width="100%" height="515" src="https://www.youtube.com/embed/F5__shDTYMQ?si=KypU241H9b2FDNUL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
++++

== Referencias

- https://stackoverflow.com/questions/53007782/what-benefits-does-chisel-offer-over-classic-hardware-description-languages
- https://github.com/chisel-crew/chisel-hello
- https://retrorgb.com/mister.html
- https://en.wikipedia.org/wiki/Field-programmable_gate_array
