= Dashboards

En esta página, exploraremos diferentes plataformas y herramientas para la visualización y gestión de datos de dispositivos IoT, incluyendo una guía para integrar datos de un ESP32 con Grafana.

== ThingsBoard

ThingsBoard es una plataforma IoT open-source que facilita la gestión de dispositivos, así como la recolección, procesamiento y visualización de datos.

Sus funcionalidades clave incluyen:

*   Un motor de reglas flexible para el procesamiento de datos complejos.
*   Dashboards IoT en tiempo real y dashboards SCADA para entornos industriales.
*   Capacidades robustas de aprovisionamiento y monitoreo de entidades IoT.

Más información en el https://github.com/thingsboard/thingsboard[repositorio de GitHub de ThingsBoard].

== OpenRemote

OpenRemote es una plataforma IoT de código abierto e intuitiva, diseñada para construir soluciones completas de gestión de dispositivos. Ofrece un control más granular para equipos internos en comparación con plataformas como ThingsBoard.

Características destacadas de OpenRemote:

*   Aprovisionamiento automático de dispositivos.
*   Personalización de tipos de activos.
*   Automatización avanzada mediante reglas "cuando-entonces", flujos y scripts en JavaScript.
*   Herramientas de análisis de datos.
*   Conectividad a través de múltiples protocolos.
*   Gestión de usuarios y roles.

Más información en el https://github.com/openremote/openremote[repositorio de GitHub de OpenRemote].
