= Introducción a la Electrónica

¿Qué es la electrónica?. Es el campo de la ingeniería
y de la física aplicada que estudia el diseño y fabricación de
circuitos y dispositivos electrónicos. A través de la electrónica es
posible medir y procesar señales para luego realizar
acciones sobre el mundo.

La electrónica ofrece una cantidad de opciones increíbles para capturar señales,
procesarlas y entregarlas de vuelta. Estos apuntes no son un
curso profundo de electrónica. En este apartado vamos a dar una pequeña pincelada a la electrónica tratando de ver cómo aplicarla en
su forma más sencilla a proyectos electromecánicos que podamos tener.

== ¿Cómo se pasa del mundo físico al eléctrico?

La electrónica se nos presenta como una herramienta muy versátil que nos
permite hacer un montón de cosas. Por ejemplo, podemos adquirir señales;
podemos tomar señales del mundo físico y llevarlas al mundo electrónico. Podemos procesar información. Eso también nos permite, por supuesto, trabajar sobre esas
señales que hemos adquirido. Y luego esas señales nos permiten
realizar acciones sobre el mundo físico. Entonces, es un lazo que
parte desde la adquisición, luego sigue con el procesamiento,
y, posteriormente, continúa con la realización de
acciones a través de señales. La electrónica nos permite
disponer de un ejército de electrones anónimos que trabajan para uno. Todos estos millones de electrones están trabajando para lo que se les programe. 

=== Sensores

Sensores y transductores, estos son los que nos permiten adquirir señales, y funcionan para diferentes variables. Sensores de temperatura, presión, sonido, luz, distancia,
aceleración, ángulo, contacto, señales eléctricas, gas,
partículas, etcétera. Existen muchos otros tipos de sensores que nos permiten capturar
señales desde el mundo físico. 


=== Procesadores

Luego tenemos el procesador que
permite procesar información. Hay diversos tipos, analógicos,
digitales; y, dentro de los digitales, están programables o no programables,
están los procesadores incrustado, que son parte de un sistema
electrónico más complicado, que puede incluir sensores y actuadores. Existen procesadores de
propósito general y, en general, estos procesadores nos permiten
diversos niveles de prestaciones. Existen procesadores con miles de millones
de compuertas lógicas, literalmente. En cambio, nosotros podemos
usar procesadores analógicos, que pueden incluir, por ejemplo, un par
de operaciones matemáticas y puede ser suficiente para hacer algo. 

.Tipos de Procesador
|====
|Ítem|Descripción

|Circuito Integrado (IC) | Un circuito integrado (CI), también conocido como chip o microchip, 
es una estructura de pequeñas dimensiones de material semiconductor, habitualmente silicio. (https://es.wikipedia.org/wiki/Circuito_integrado[IC, Wikipedia]).
Uno de los más comunes es el temporizador IC 555, 
que se utiliza en la generación de temporizadores, pulsos y oscilaciones. 
El 555 puede ser utilizado para proporcionar retardos de tiempo, como un oscilador, y como un 
circuito integrado flip flop. (https://es.wikipedia.org/wiki/Circuito_integrado_555[IC555, Wikipedia]).
Si bien no es un procesador, es un componente importante de ellos y se pueden realizar múltiples proyectos
solo usando este microchip.

|Procesador Analógico | Los ejemplos de procesamiento analógico de señales incluyen: el filtro pasa banda y filtro 
pasa bajos, entre otros filtros de señales para baja frecuencia y radio frecuencia, 
los controles de volumen, graves y agudos en equipos de música, y los controles de contraste y brillo 
en los televisores. El procesamiento analógico de la señal incluye elementos comunes como 
capacitores, resistencias, inductores, transistores o circuitos integrados. (https://es.wikipedia.org/wiki/Procesamiento_anal%C3%B3gico_de_se%C3%B1ales[Procesador Analógico, Wikipedia]).

| Procesador Digital No Programable | 
Un procesador digital no programable es un dispositivo digital que realiza tareas específicas 
sin la posibilidad de ser reprogramado por el usuario. En otras palabras, su función está definida por 
su hardware y no por software o instrucciones que puedan ser modificadas. 
Ejemplos: FPGAs (Field-Programmable Gate Arrays), ASICs (Application-Specific Integrated Circuits), Procesadores de Señales Digitales (DSP).
(https://es.wikipedia.org/wiki/Procesador_de_se%C3%B1ales_digitales[DSP, Wikipedia]).

| Procesador Digital Programable |
Un procesador digital programable (PDSP) es un microprocesador de propósito general, diseñado específicamente para aplicaciones de procesamiento de señales digitales (DSP). Estos procesadores permiten realizar operaciones numéricas a alta velocidad sobre señales digitales, como audio, 
video o datos de sensores, para tareas como filtrado, ecualización, compresión, entre otras. (https://es.wikipedia.org/wiki/Procesador_de_se%C3%B1ales_digitales[DSP, Wikipedia])

| Microcontrolador |
La principal diferencia entre un microprocesador y un microcontrolador radica en su diseño y aplicación. 
Un microprocesador es un procesador de propósito general que se utiliza en computadoras y otros 
dispositivos que requieren potencia de cálculo considerable. Los microcontroladores, por otro lado, 
son circuitos integrados que integran un procesador, memoria y periféricos en un solo chip, 
diseñados para aplicaciones específicas e incrustadas. (https://aws.amazon.com/es/compare/the-difference-between-microprocessors-microcontrollers/[Microcontrolador vs Microprocesador, AWS])
Entre ellos el màs popular es el _PIC16f877a_, un microcontrolador de 8 bits de la familia PIC 
ideal para proyectos simples, debido a su arquitectura de 8 bits, 18 pines, y un 
conjunto de instrucciones RISC muy amigable para memorizar y fácil de entender. (https://es.wikipedia.org/wiki/PIC16F87X[PIC1687X, Wikipedia])

|====

=== Actuadores y Transductores

Luego tenemos actuadores y transductores (dispositivo que transforma una forma de energía en otra)
que nos permiten realizar acciones. Tenemos de diverso tipo, sonido,
por ejemplo, un parlante; transductores de luz como, por ejemplo, encender una luz que
indique algo, o pueden ser también una pantalla donde yo puedo mirar algo, y esto
también es una forma de un transductor. de luz que tiene diferentes píxeles. Cada uno de estos puntos de la pantalla es
un píxel y cada uno de estos se ilumina independientemente. 

Existen también actuadores de movimiento como,
por ejemplo, un motor, que nos permite realizar acciones físicas. Existen transductores de calor como una estufa o una resistencia eléctrica, entre otros.

=== Electricidad

La electricidad es crucial cuando
queremos procesar información; cuando pensamos en capturar, procesar
o entregar señales, esto es sensor, procesar, procesador, y entregar señales a través de un
actuador, inevitablemente, terminamos pensando en el uso de la electricidad y
¿por qué será eso?, ¿por qué no podemos, por ejemplo, capturar señales en
otro medio, que no sea eléctrico? Podríamos hacerlo tal vez
en un medio hidráulico, o un medio mecánico o, tal vez,
de otra forma, en un medio óptico. El problema es que los fotones viajan
a la velocidad de la luz y luego se van; en caso del sistema mecánico, a veces es muy complicado hacer que un
sistema mecánico opere rápidamente; en caso de la electricidad, las respuestas
son comparables a las de la velocidad de la luz pero,
además, podemos guardar señales, y eso permite un nivel de procesamiento que
solo la electricidad es capaz de otorgar.

=== Esquema de un Sistema Electrónico

El siguiente esquema presenta el funcionamiento de un sistema electrónico en general. Los sensores son los que nos permiten *capturar* señales del mundo físico; el procesador, que nos permite *procesar* estas señales y, luego, los actuadores, que nos permiten *actuar* sobre el mundo físico.

.Esquema General de Sistema Electrónico
[plantuml]
----
@startuml

autonumber

Sensor -> Procesador: señal

activate Procesador
Procesador -> Procesador: procesamiento
Procesador -> Actuador: señal

activate Actuador
Actuador --> Actuador: acción


@enduml
----

include::scientists.adoc[]
