= Introducción a la Electrónica

¿Qué es la electrónica?. Es el campo de la ingeniería
y de la física aplicada que estudia el diseño y fabricación de
circuitos y dispositivos electrónicos. A través de la electrónica es
posible medir y procesar señales para luego realizar
acciones sobre el mundo.

La electrónica ofrece una cantidad de opciones increíbles para capturar señales,
procesarlas y entregarlas de vuelta. Estos apuntes no son un
curso profundo de electrónica. En este apartado vamos a dar una pequeña pincelada a la electrónica tratando de ver cómo aplicarla en
su forma más sencilla a proyectos electromecánicos que podamos tener.

== ¿Cómo se pasa del mundo físico al eléctrico?

La electrónica se nos presenta como una herramienta muy versátil que nos
permite hacer un montón de cosas. Por ejemplo, podemos adquirir señales;
podemos tomar señales del mundo físico y llevarlas al mundo electrónico. Podemos procesar información. Eso también nos permite, por supuesto, trabajar sobre esas
señales que hemos adquirido. Y luego esas señales nos permiten
realizar acciones sobre el mundo físico. Entonces, es un lazo que
parte desde la adquisición, luego sigue con el procesamiento,
y, posteriormente, continúa con la realización de
acciones a través de señales. La electrónica nos permite
disponer de un ejército de electrones anónimos que trabajan para uno. Todos estos millones de electrones están trabajando para lo que se les programe. 

=== Sensores

Sensores y transductores, estos son los que nos permiten adquirir señales, y funcionan para diferentes variables. Sensores de temperatura, presión, sonido, luz, distancia,
aceleración, ángulo, contacto, señales eléctricas, gas,
partículas, etcétera. Existen muchos otros tipos de sensores que nos permiten capturar
señales desde el mundo físico. 


=== Procesadores

Luego tenemos el procesador que
permite procesar información. Hay diversos tipos, analógicos,
digitales; y, dentro de los digitales, están programables o no programables,
están los procesadores incrustado, que son parte de un sistema
electrónico más complicado, que puede incluir sensores y actuadores. Existen procesadores de
propósito general y, en general, estos procesadores nos permiten
diversos niveles de prestaciones. Existen procesadores con miles de millones
de compuertas lógicas, literalmente. En cambio, nosotros podemos
usar procesadores analógicos, que pueden incluir, por ejemplo, un par
de operaciones matemáticas y puede ser suficiente para hacer algo. 


=== Actuadores y Transductores

Luego tenemos actuadores y transductores
que nos permiten realizar acciones. Tenemos de diverso tipo, sonido,
por ejemplo, un parlante; transductores de luz como, por ejemplo, encender una luz que
indique algo, o pueden ser también una pantalla donde yo puedo mirar algo, y esto
también es una forma de un transductor. de luz que tiene diferentes píxeles. Cada uno de estos puntos de la pantalla es
un píxel y cada uno de estos se ilumina independientemente. 

Existen también actuadores de movimiento como,
por ejemplo, un motor, que nos permite realizar acciones físicas. Existen transductores de calor como una estufa o una resistencia eléctrica, entre otros.

=== Electricidad

La electricidad es crucial cuando
queremos procesar información; cuando pensamos en capturar, procesar
o entregar señales, esto es sensor, procesar, procesador, y entregar señales a través de un
actuador, inevitablemente, terminamos pensando en el uso de la electricidad y
¿por qué será eso?, ¿por qué no podemos, por ejemplo, capturar señales en
otro medio, que no sea eléctrico? Podríamos hacerlo tal vez
en un medio hidráulico, o un medio mecánico o, tal vez,
de otra forma, en un medio óptico. El problema es que los fotones viajan
a la velocidad de la luz y luego se van; en caso del sistema mecánico, a veces es muy complicado hacer que un
sistema mecánico opere rápidamente; en caso de la electricidad, las respuestas
son comparables a las de la velocidad de la luz pero,
además, podemos guardar señales, y eso permite un nivel de procesamiento que
solo la electricidad es capaz de otorgar.

=== Esquema de un Sistema Electrónico

El siguiente esquema presenta el funcionamiento de un sistema electrónico en general. Los sensores son los que nos permiten *capturar* señales del mundo físico; el procesador, que nos permite *procesar* estas señales y, luego, los actuadores, que nos permiten *actuar* sobre el mundo físico.

.Esquema General de Sistema Electrónico
[plantuml]
----
@startuml

autonumber

Sensor -> Procesador: señal

activate Procesador
Procesador -> Procesador: procesamiento
Procesador -> Actuador: señal

activate Actuador
Actuador --> Actuador: acción


@enduml
----